"""Tests for the hard contract gate between `kite.backend` and `kite.frontend`."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest
import yaml


pytestmark = pytest.mark.skipif(
    sys.platform.startswith("win"),
    reason="contract gate is a bash script; Windows runners may not have bash on PATH",
)


REPO_ROOT = Path(__file__).resolve().parent.parent
KITE_WF = REPO_ROOT / "workflows" / "kite" / "workflow.yml"


@pytest.fixture(scope="module")
def gate_script() -> str:
    wf = yaml.safe_load(KITE_WF.read_text(encoding="utf-8"))
    gate = next(s for s in wf["steps"] if s.get("id") == "contract-gate")
    assert gate["type"] == "shell"
    return gate["run"]


def _run_gate(gate_script: str, cwd: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["bash", "-c", gate_script],
        cwd=cwd,
        capture_output=True,
        text=True,
    )


def _complete_contract() -> str:
    return """# Frontend Contract

**Stage:** backend
**Generated by:** kite.backend

## What this means in plain English

The dashboard gets item data from the API and displays errors from a shared response shape.

## 1. Base URL & auth

- **Base URL:** http://localhost:8000
- **Auth:** none

## 2. Endpoints

### List items

- **Plain English:** Returns visible items for the dashboard.
- **Method + path:** `GET /api/items`
- **Query / body:** none
- **Returns (200):**
  ```json
  { "items": [{ "id": "string", "name": "string" }] }
  ```
- **Errors:** `500` for unexpected server errors.

## 3. Shared data shapes

Item has id and name fields.

## 4. State changes / events

None - pure request/response.

## 5. Error contract

Errors return `{ "error": { "message": "string", "code": "string" } }`.

## 6. Frontend usage map

- Dashboard screen uses `GET /api/items` through `frontend/src/lib/api.ts`.

## 7. Local verification commands

- Start backend: `uvicorn app:app --reload`
- Verify endpoint: `curl http://localhost:8000/api/items`

## 8. Auth flows

None.

## 9. Non-goals

No item editing in this iteration.

## 10. Versioning

Breaking changes bump the path prefix to `/api/v2/...`.

## 11. Notes

None.
"""


class TestContractGateAborts:
    def test_aborts_when_no_specs_directory(self, gate_script: str, tmp_path: Path):
        result = _run_gate(gate_script, tmp_path)
        assert result.returncode != 0
        assert "no active specs" in result.stderr.lower()

    def test_aborts_when_contract_missing(self, gate_script: str, tmp_path: Path):
        spec_dir = tmp_path / "specs" / "001-demo"
        spec_dir.mkdir(parents=True)
        (spec_dir / "spec.md").write_text("# spec", encoding="utf-8")

        result = _run_gate(gate_script, tmp_path)

        assert result.returncode != 0
        assert "contract.md" in result.stderr
        assert "missing" in result.stderr.lower()

    def test_aborts_when_contract_has_todo(self, gate_script: str, tmp_path: Path):
        spec_dir = tmp_path / "specs" / "001-demo"
        spec_dir.mkdir(parents=True)
        (spec_dir / "contract.md").write_text(
            "# Contract\n\n## Endpoint\n\nTODO: fill in\n",
            encoding="utf-8",
        )

        result = _run_gate(gate_script, tmp_path)

        assert result.returncode != 0
        assert "placeholder" in result.stderr.lower() or "todo" in result.stderr.lower()

    def test_aborts_when_contract_has_angle_placeholder(self, gate_script: str, tmp_path: Path):
        spec_dir = tmp_path / "specs" / "001-demo"
        spec_dir.mkdir(parents=True)
        (spec_dir / "contract.md").write_text(
            "# Contract\n\nGET /api/<resource> returns <payload>.\n",
            encoding="utf-8",
        )

        result = _run_gate(gate_script, tmp_path)

        assert result.returncode != 0

    def test_aborts_when_required_contract_section_missing(self, gate_script: str, tmp_path: Path):
        spec_dir = tmp_path / "specs" / "001-demo"
        spec_dir.mkdir(parents=True)
        contract = _complete_contract().replace("## 6. Frontend usage map\n\n- Dashboard screen uses `GET /api/items` through `frontend/src/lib/api.ts`.\n\n", "")
        (spec_dir / "contract.md").write_text(contract, encoding="utf-8")

        result = _run_gate(gate_script, tmp_path)

        assert result.returncode != 0
        assert "Frontend usage map" in result.stderr

    def test_aborts_when_endpoint_lacks_method_path(self, gate_script: str, tmp_path: Path):
        spec_dir = tmp_path / "specs" / "001-demo"
        spec_dir.mkdir(parents=True)
        contract = _complete_contract().replace("- **Method + path:** `GET /api/items`\n", "")
        (spec_dir / "contract.md").write_text(contract, encoding="utf-8")

        result = _run_gate(gate_script, tmp_path)

        assert result.returncode != 0
        assert "Method + path" in result.stderr

    def test_aborts_when_any_endpoint_lacks_method_path(self, gate_script: str, tmp_path: Path):
        spec_dir = tmp_path / "specs" / "001-demo"
        spec_dir.mkdir(parents=True)
        contract = _complete_contract().replace(
            "## 3. Shared data shapes",
            "### Create item\n\n"
            "- **Plain English:** Creates an item from the form.\n"
            "- **Query / body:** JSON item payload.\n"
            "- **Returns (201):** Created item.\n\n"
            "## 3. Shared data shapes",
        )
        (spec_dir / "contract.md").write_text(contract, encoding="utf-8")

        result = _run_gate(gate_script, tmp_path)

        assert result.returncode != 0
        assert "Method + path" in result.stderr


class TestContractGatePasses:
    def test_passes_when_contract_complete(self, gate_script: str, tmp_path: Path):
        spec_dir = tmp_path / "specs" / "001-demo"
        spec_dir.mkdir(parents=True)
        (spec_dir / "contract.md").write_text(_complete_contract(), encoding="utf-8")

        result = _run_gate(gate_script, tmp_path)

        assert result.returncode == 0, f"stderr: {result.stderr}"
        assert "OK" in result.stdout

    def test_uses_latest_spec_directory_only_as_fallback(self, gate_script: str, tmp_path: Path):
        old = tmp_path / "specs" / "001-old"
        old.mkdir(parents=True)
        (old / "contract.md").write_text("TODO\n", encoding="utf-8")

        new = tmp_path / "specs" / "002-new"
        new.mkdir(parents=True)
        (new / "contract.md").write_text(_complete_contract(), encoding="utf-8")

        result = _run_gate(gate_script, tmp_path)

        assert result.returncode == 0, f"stderr: {result.stderr}"

    def test_latest_fallback_uses_numeric_sort(self, gate_script: str, tmp_path: Path):
        old = tmp_path / "specs" / "999-old"
        old.mkdir(parents=True)
        (old / "contract.md").write_text("TODO\n", encoding="utf-8")

        new = tmp_path / "specs" / "1000-new"
        new.mkdir(parents=True)
        (new / "contract.md").write_text(_complete_contract(), encoding="utf-8")

        result = _run_gate(gate_script, tmp_path)

        assert result.returncode == 0, f"stderr: {result.stderr}"

    def test_uses_feature_json_before_latest_spec_directory(self, gate_script: str, tmp_path: Path):
        kite_dir = tmp_path / ".kite"
        kite_dir.mkdir()
        active = tmp_path / "specs" / "001-active"
        active.mkdir(parents=True)
        (active / "contract.md").write_text("TODO\n", encoding="utf-8")
        (kite_dir / "feature.json").write_text(
            '{"feature_directory":"specs/001-active"}',
            encoding="utf-8",
        )

        later = tmp_path / "specs" / "002-later"
        later.mkdir(parents=True)
        (later / "contract.md").write_text(_complete_contract(), encoding="utf-8")

        result = _run_gate(gate_script, tmp_path)

        assert result.returncode != 0
        assert "001-active" in result.stderr
